"""empty message

Revision ID: 0555db125011
Revises: d543c6a2ea6e
Create Date: 2017-02-28 00:46:16.624939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0555db125011'
down_revision = 'd543c6a2ea6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocoltypes', sa.Column('calendar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocoltypes', 'calendar')
    # ### end Alembic commands ###
