"""empty message

Revision ID: 0686095ee9dd
Revises: 60a730d37c9a
Create Date: 2017-04-28 22:24:35.628585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0686095ee9dd'
down_revision = '60a730d37c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocols', sa.Column('content_html_private', sa.String(), nullable=True))
    op.add_column('protocols', sa.Column('content_html_public', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocols', 'content_html_public')
    op.drop_column('protocols', 'content_html_private')
    # ### end Alembic commands ###
