"""empty message

Revision ID: 162da8aeeb71
Revises: a3d9d1b87ba0
Create Date: 2017-02-22 16:52:08.142214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '162da8aeeb71'
down_revision = 'a3d9d1b87ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingreminders', sa.Column('days_before', sa.Integer(), nullable=True))
    op.drop_column('meetingreminders', 'time_before')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingreminders', sa.Column('time_before', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    op.drop_column('meetingreminders', 'days_before')
    # ### end Alembic commands ###
