"""empty message

Revision ID: 24bd2198a626
Revises: 2e2682dfac21
Create Date: 2017-02-24 17:20:07.135782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bd2198a626'
down_revision = '2e2682dfac21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'number')
    # ### end Alembic commands ###
