"""empty message

Revision ID: 2e2682dfac21
Revises: aebae2c4523d
Create Date: 2017-02-24 16:31:01.729972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2682dfac21'
down_revision = 'aebae2c4523d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('is_id_fixed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'is_id_fixed')
    # ### end Alembic commands ###
