"""empty message

Revision ID: 310d9ab321b8
Revises: 0131d5776f8d
Create Date: 2017-02-25 17:26:34.663460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310d9ab321b8'
down_revision = '0131d5776f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocols', sa.Column('plain_text_private', sa.String(), nullable=True))
    op.add_column('protocols', sa.Column('plain_text_public', sa.String(), nullable=True))
    op.drop_column('todos', 'is_id_fixed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('is_id_fixed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('protocols', 'plain_text_public')
    op.drop_column('protocols', 'plain_text_private')
    # ### end Alembic commands ###
