"""empty message

Revision ID: 4b813bbbd8ef
Revises: 8fdd381e6a2a
Create Date: 2017-03-15 02:18:24.986531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b813bbbd8ef'
down_revision = '8fdd381e6a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisioncategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocoltype_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['protocoltype_id'], ['protocoltypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('decisions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'decisions', 'decisioncategories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decisions', type_='foreignkey')
    op.drop_column('decisions', 'category_id')
    op.drop_table('decisioncategories')
    # ### end Alembic commands ###
