"""empty message

Revision ID: 60a730d37c9a
Revises: ac54a2c29610
Create Date: 2017-04-28 22:10:24.694024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a730d37c9a'
down_revision = 'ac54a2c29610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('decisions_category_id_fkey', 'decisions', type_='foreignkey')
    op.drop_column('decisions', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('decisions_category_id_fkey', 'decisions', 'decisioncategories', ['category_id'], ['id'])
    # ### end Alembic commands ###
