"""empty message

Revision ID: 70547c924023
Revises: 4e472894cc70
Create Date: 2017-04-17 23:31:58.499305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70547c924023'
down_revision = '4e472894cc70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defaultmetas', sa.Column('prior', sa.Boolean(), nullable=False))
    op.add_column('defaultmetas', sa.Column('value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defaultmetas', 'value')
    op.drop_column('defaultmetas', 'prior')
    # ### end Alembic commands ###
