"""empty message

Revision ID: 77bf71eef07f
Revises: f91d760158dc
Create Date: 2017-02-26 00:26:48.499578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77bf71eef07f'
down_revision = 'f91d760158dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingreminders', sa.Column('additional_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingreminders', 'additional_text')
    # ### end Alembic commands ###
