"""empty message

Revision ID: 984d75352ea1
Revises: da846db78ff9
Create Date: 2025-06-11 22:42:13.227657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984d75352ea1'
down_revision = 'da846db78ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocoltypes', sa.Column('gitlab_api_token', sa.Text(), nullable=True))
    op.add_column('protocoltypes', sa.Column('gitlab_project_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocoltypes', 'gitlab_project_id')
    op.drop_column('protocoltypes', 'gitlab_api_token')
    # ### end Alembic commands ###
