"""empty message

Revision ID: a1f23743bddb
Revises: 0555db125011
Create Date: 2017-02-28 13:38:25.900461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f23743bddb'
down_revision = '0555db125011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocols', sa.Column('public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocols', 'public')
    # ### end Alembic commands ###
