"""empty message

Revision ID: a3d9d1b87ba0
Revises: efaa3b4fd3e8
Create Date: 2017-02-22 16:00:02.816515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d9d1b87ba0'
down_revision = 'efaa3b4fd3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocols', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocols', 'done')
    # ### end Alembic commands ###
