"""empty message

Revision ID: ab996d2365af
Revises: a1f23743bddb
Create Date: 2017-03-01 03:27:25.199271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab996d2365af'
down_revision = 'a1f23743bddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tops', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tops', 'description')
    # ### end Alembic commands ###
