"""empty message

Revision ID: ac54a2c29610
Revises: c59998057d39
Create Date: 2017-04-20 19:30:26.887146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac54a2c29610'
down_revision = 'c59998057d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisioncategoryassociations',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('decisioncategory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['decisioncategory_id'], ['decisioncategories.id'], ),
    sa.PrimaryKeyConstraint('decision_id', 'decisioncategory_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decisioncategoryassociations')
    # ### end Alembic commands ###
