"""empty message

Revision ID: b4156f71ee73
Revises: 7dd3c479c048
Create Date: 2017-03-01 04:24:24.534003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4156f71ee73'
down_revision = '7dd3c479c048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defaultmeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocoltype_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['protocoltype_id'], ['protocoltypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta')
    op.drop_table('defaultmeta')
    # ### end Alembic commands ###
