"""empty message

Revision ID: cd972745eb09
Revises: 0068d7a0fac0
Create Date: 2017-03-09 03:35:22.809679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd972745eb09'
down_revision = '0068d7a0fac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocoltypes', sa.Column('non_reproducible_pad_links', sa.Boolean(), nullable=True, server_default=sa.sql.expression.literal(False)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocoltypes', 'non_reproducible_pad_links')
    # ### end Alembic commands ###
