"""empty message

Revision ID: d8c0c74b88bd
Revises: 495509e8f49a
Create Date: 2017-02-25 20:16:05.371638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c0c74b88bd'
down_revision = '495509e8f49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocoltypes', sa.Column('use_wiki', sa.Boolean(), nullable=True))
    op.add_column('protocoltypes', sa.Column('wiki_category', sa.String(), nullable=True))
    op.add_column('protocoltypes', sa.Column('wiki_only_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocoltypes', 'wiki_only_public')
    op.drop_column('protocoltypes', 'wiki_category')
    op.drop_column('protocoltypes', 'use_wiki')
    # ### end Alembic commands ###
