"""empty message

Revision ID: da846db78ff9
Revises: 7834767242e8
Create Date: 2022-10-29 19:24:42.934124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da846db78ff9'
down_revision = '7834767242e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocoltypes', sa.Column('recurrence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocoltypes', 'recurrence')
    # ### end Alembic commands ###
