"""empty message

Revision ID: f91d760158dc
Revises: d8c0c74b88bd
Create Date: 2017-02-25 21:52:07.654276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91d760158dc'
down_revision = 'd8c0c74b88bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocoltypes', sa.Column('printer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocoltypes', 'printer')
    # ### end Alembic commands ###
