"""empty message

Revision ID: 15e172ac1a28
Revises: 841fb7253188
Create Date: 2019-06-17 17:58:50.754148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e172ac1a28'
down_revision = '841fb7253188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oldtodos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_id', sa.Integer(), nullable=True),
    sa.Column('who', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('protocol_key', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oldtodos')
    # ### end Alembic commands ###
