"""empty message

Revision ID: 841fb7253188
Revises: 
Create Date: 2018-11-09 18:49:39.933529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841fb7253188'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocoltypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('short_name', sa.String(length=128), nullable=True),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('usual_time', sa.Time(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('modify_group', sa.Text(), nullable=True),
    sa.Column('private_group', sa.Text(), nullable=True),
    sa.Column('public_group', sa.Text(), nullable=True),
    sa.Column('publish_group', sa.Text(), nullable=True),
    sa.Column('private_mail', sa.Text(), nullable=True),
    sa.Column('public_mail', sa.Text(), nullable=True),
    sa.Column('non_reproducible_pad_links', sa.Boolean(), nullable=True),
    sa.Column('use_wiki', sa.Boolean(), nullable=True),
    sa.Column('wiki_category', sa.Text(), nullable=True),
    sa.Column('wiki_only_public', sa.Boolean(), nullable=True),
    sa.Column('printer', sa.Text(), nullable=True),
    sa.Column('calendar', sa.Text(), nullable=True),
    sa.Column('restrict_networks', sa.Boolean(), nullable=True),
    sa.Column('allowed_networks', sa.Text(), nullable=True),
    sa.Column('latex_template', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('todomails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('mail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('decisioncategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocoltype_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['protocoltype_id'], ['protocoltypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defaultmetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocoltype_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('internal', sa.Boolean(), nullable=True),
    sa.Column('prior', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['protocoltype_id'], ['protocoltypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defaulttops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocoltype_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['protocoltype_id'], ['protocoltypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetingreminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocoltype_id', sa.Integer(), nullable=True),
    sa.Column('days_before', sa.Integer(), nullable=True),
    sa.Column('send_public', sa.Boolean(), nullable=True),
    sa.Column('send_private', sa.Boolean(), nullable=True),
    sa.Column('additional_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['protocoltype_id'], ['protocoltypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocoltype_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('content_public', sa.Text(), nullable=True),
    sa.Column('content_private', sa.Text(), nullable=True),
    sa.Column('content_html_public', sa.Text(), nullable=True),
    sa.Column('content_html_private', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('pad_identifier', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['protocoltype_id'], ['protocoltypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocoltype_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('who', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('open', 'waiting', 'in_progress', 'after', 'before', 'orphan', 'done', 'rejected', 'obsolete', name='todostate'), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['protocoltype_id'], ['protocoltypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('is_compiled', sa.Boolean(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likeprotocolassociations',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['like_id'], ['likes.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('like_id', 'protocol_id')
    )
    op.create_table('liketodoassociations',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['like_id'], ['likes.id'], ),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ),
    sa.PrimaryKeyConstraint('like_id', 'todo_id')
    )
    op.create_table('localtops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('defaulttop_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['defaulttop_id'], ['defaulttops.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('internal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todoprotocolassociations',
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ),
    sa.PrimaryKeyConstraint('todo_id', 'protocol_id')
    )
    op.create_table('tops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('planned', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisioncategoryassociations',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('decisioncategory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['decisioncategory_id'], ['decisioncategories.id'], ),
    sa.PrimaryKeyConstraint('decision_id', 'decisioncategory_id')
    )
    op.create_table('decisiondocuments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likedecisionassociations',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['like_id'], ['likes.id'], ),
    sa.PrimaryKeyConstraint('like_id', 'decision_id')
    )
    op.create_table('liketopassociations',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('top_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['like_id'], ['likes.id'], ),
    sa.ForeignKeyConstraint(['top_id'], ['tops.id'], ),
    sa.PrimaryKeyConstraint('like_id', 'top_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liketopassociations')
    op.drop_table('likedecisionassociations')
    op.drop_table('decisiondocuments')
    op.drop_table('decisioncategoryassociations')
    op.drop_table('tops')
    op.drop_table('todoprotocolassociations')
    op.drop_table('metas')
    op.drop_table('localtops')
    op.drop_table('liketodoassociations')
    op.drop_table('likeprotocolassociations')
    op.drop_table('errors')
    op.drop_table('documents')
    op.drop_table('decisions')
    op.drop_table('todos')
    op.drop_table('protocols')
    op.drop_table('meetingreminders')
    op.drop_table('defaulttops')
    op.drop_table('defaultmetas')
    op.drop_table('decisioncategories')
    op.drop_table('todomails')
    op.drop_table('protocoltypes')
    # ### end Alembic commands ###
